CREATE TABLE MARRIAGES (
    MARRIAGE_ID INTEGER NOT NULL PRIMARY KEY
        GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1),
    'FROM' DATE NOT NULL,
    'TO' DATE,
    SPOUSE1_ID INTEGER NOT NULL,
    SPOUSE2_ID INTEGER NOT NULL,
    CONSTRAINT SPOUSE1_FK
        FOREIGN KEY (SPOUSE1_ID)
        REFERENCES PEOPLE (ID),
    CONSTRAINT SPOUSE2_FK
        FOREIGN KEY (SPOUSE2_ID)
        REFERENCES PEOPLE (ID)
)