CREATE TABLE RELATIONS (
    PARENT_ID INTEGER NOT NULL,
    CHILD_ID INTEGER NOT NULL,
    CONSTRAINT REL_ID PRIMARY KEY (PARENT_ID, CHILD_ID),
    CONSTRAINT PARENT_FK
        FOREIGN KEY (PARENT_ID)
        REFERENCES PEOPLE (ID),
    CONSTRAINT CHILD_FK
        FOREIGN KEY (CHILD_ID)
        REFERENCES PEOPLE (ID)
)