CREATE TABLE PEOPLE (
    ID INTEGER NOT NULL PRIMARY KEY
        GENERATED ALWAYS AS IDENTITY
        (START WITH 1, INCREMENT BY 1),
    NAME VARCHAR(50),
    GENDER VARCHAR(10),
    BIRTHDATE DATE,
    BIRTHPLACE VARCHAR(50),
    DEATHDATE DATE,
    DEATHPLACE VARCHAR(50)
)