/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cz.muni.fi.pv168.familytree.gui;

/**
 *
 * @author Peter
 */
public class FamilyTreeGUI extends javax.swing.JFrame {

    /**
     * Creates new form FamilyTreeGUI
     */
    public FamilyTreeGUI() {
        initComponents();
        fixInitComponents();
    }
    
    private void fixInitComponents() { //To localize table heads. Wasnt able to find other way
        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("localization"); // NOI18N
        
        peopleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                bundle.getString("peopleTableName"), bundle.getString("peopleTableGender"), bundle.getString("peopleTableDateOfBirth"),
                bundle.getString("peopleTablePlaceOfBirth"), bundle.getString("peopleTableDateOfDeath"), bundle.getString("peopleTablePlaceOfDeath")
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        
        marriagesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                bundle.getString("marriagesTableSpouse1"), bundle.getString("marriagesTableSpouse2"), 
                bundle.getString("marriagesTableFrom"), bundle.getString("marriagesTableTo")
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        
        relationsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                bundle.getString("relationsTableChildName"), bundle.getString("relationsTableParentName")
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        peoplePanel = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        peopleTable = new javax.swing.JTable();
        marriagesPanel = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        marriagesTable = new javax.swing.JTable();
        relationsPanel = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        relationsTable = new javax.swing.JTable();
        treePanel = new javax.swing.JPanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        menuBar = new javax.swing.JMenuBar();
        fileMenu = new javax.swing.JMenu();
        newFileMenuItem = new javax.swing.JMenuItem();
        jSeparator1 = new javax.swing.JPopupMenu.Separator();
        openFileMenuItem = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JPopupMenu.Separator();
        saveFileMenuItem = new javax.swing.JMenuItem();
        saveFileAsMenuItem = new javax.swing.JMenuItem();
        jSeparator3 = new javax.swing.JPopupMenu.Separator();
        exitMenuItem = new javax.swing.JMenuItem();
        editMenu = new javax.swing.JMenu();
        undoMenuItem = new javax.swing.JMenuItem();
        redoMenuItem = new javax.swing.JMenuItem();
        manageMenu = new javax.swing.JMenu();
        createPersonMenuItem = new javax.swing.JMenuItem();
        updatePersonMenuItem = new javax.swing.JMenuItem();
        deletePersonMenuItem = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JPopupMenu.Separator();
        createMarriageMenuItem = new javax.swing.JMenuItem();
        updateMarriageMenuItem = new javax.swing.JMenuItem();
        deleteMarriageMenuItem = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JPopupMenu.Separator();
        createRelationMenuItem = new javax.swing.JMenuItem();
        deleteRelationMenuItem = new javax.swing.JMenuItem();
        findMenu = new javax.swing.JMenu();
        findPersonMenuItem = new javax.swing.JMenuItem();
        findMarriageMenuItem = new javax.swing.JMenuItem();
        findRelationMenuItem = new javax.swing.JMenuItem();
        helpMenu = new javax.swing.JMenu();
        aboutMenuItem = new javax.swing.JMenuItem();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Family Tree App");
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        peopleTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Name", "Gender", "Birth Date", "Birth Place", "Death Date", "Death Place"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(peopleTable);

        javax.swing.GroupLayout peoplePanelLayout = new javax.swing.GroupLayout(peoplePanel);
        peoplePanel.setLayout(peoplePanelLayout);
        peoplePanelLayout.setHorizontalGroup(
            peoplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(peoplePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 558, Short.MAX_VALUE)
                .addGap(7, 7, 7))
        );
        peoplePanelLayout.setVerticalGroup(
            peoplePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(peoplePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                .addContainerGap())
        );

        java.util.ResourceBundle bundle = java.util.ResourceBundle.getBundle("localization"); // NOI18N
        jTabbedPane1.addTab(bundle.getString("peoplePanel"), peoplePanel); // NOI18N

        marriagesTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Spouse 1 Name", "Spouse 2 Name", "From", "To"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(marriagesTable);

        javax.swing.GroupLayout marriagesPanelLayout = new javax.swing.GroupLayout(marriagesPanel);
        marriagesPanel.setLayout(marriagesPanelLayout);
        marriagesPanelLayout.setHorizontalGroup(
            marriagesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(marriagesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                .addContainerGap())
        );
        marriagesPanelLayout.setVerticalGroup(
            marriagesPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(marriagesPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab(bundle.getString("marriagesPanel"), marriagesPanel); // NOI18N

        relationsTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Parent Name", "Child Name"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane3.setViewportView(relationsTable);

        javax.swing.GroupLayout relationsPanelLayout = new javax.swing.GroupLayout(relationsPanel);
        relationsPanel.setLayout(relationsPanelLayout);
        relationsPanelLayout.setHorizontalGroup(
            relationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(relationsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                .addContainerGap())
        );
        relationsPanelLayout.setVerticalGroup(
            relationsPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(relationsPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab(bundle.getString("relationsPanel"), relationsPanel); // NOI18N

        jScrollPane4.setBackground(new java.awt.Color(255, 255, 255));

        javax.swing.GroupLayout treePanelLayout = new javax.swing.GroupLayout(treePanel);
        treePanel.setLayout(treePanelLayout);
        treePanelLayout.setHorizontalGroup(
            treePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(treePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 553, Short.MAX_VALUE)
                .addContainerGap())
        );
        treePanelLayout.setVerticalGroup(
            treePanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(treePanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane4, javax.swing.GroupLayout.DEFAULT_SIZE, 326, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab(bundle.getString("treePanel"), treePanel); // NOI18N

        fileMenu.setMnemonic(java.awt.event.KeyEvent.VK_F);
        fileMenu.setText(bundle.getString("fileMenu")); // NOI18N

        newFileMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_N, java.awt.event.InputEvent.CTRL_MASK));
        newFileMenuItem.setMnemonic(java.awt.event.KeyEvent.VK_N);
        newFileMenuItem.setText(bundle.getString("newFileMenuItem")); // NOI18N
        newFileMenuItem.setToolTipText("");
        newFileMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newFileMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(newFileMenuItem);
        fileMenu.add(jSeparator1);

        openFileMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_O, java.awt.event.InputEvent.CTRL_MASK));
        openFileMenuItem.setMnemonic(java.awt.event.KeyEvent.VK_O);
        openFileMenuItem.setText(bundle.getString("openFileMenuItem")); // NOI18N
        openFileMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openFileMenuItemActionPerformed(evt);
            }
        });
        fileMenu.add(openFileMenuItem);
        fileMenu.add(jSeparator2);

        saveFileMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_S, java.awt.event.InputEvent.CTRL_MASK));
        saveFileMenuItem.setMnemonic(java.awt.event.KeyEvent.VK_S);
        saveFileMenuItem.setText(bundle.getString("saveFileMenuItem")); // NOI18N
        fileMenu.add(saveFileMenuItem);

        saveFileAsMenuItem.setMnemonic(java.awt.event.KeyEvent.VK_A);
        saveFileAsMenuItem.setText(bundle.getString("saveFileAsMenuItem")); // NOI18N
        fileMenu.add(saveFileAsMenuItem);
        fileMenu.add(jSeparator3);

        exitMenuItem.setMnemonic(java.awt.event.KeyEvent.VK_E);
        exitMenuItem.setText(bundle.getString("exitMenuItem")); // NOI18N
        fileMenu.add(exitMenuItem);

        menuBar.add(fileMenu);

        editMenu.setMnemonic(java.awt.event.KeyEvent.VK_E);
        editMenu.setText(bundle.getString("editMenu")); // NOI18N

        undoMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Z, java.awt.event.InputEvent.CTRL_MASK));
        undoMenuItem.setMnemonic(java.awt.event.KeyEvent.VK_U);
        undoMenuItem.setText(bundle.getString("undoMenuItem")); // NOI18N
        undoMenuItem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                undoMenuItemActionPerformed(evt);
            }
        });
        editMenu.add(undoMenuItem);

        redoMenuItem.setAccelerator(javax.swing.KeyStroke.getKeyStroke(java.awt.event.KeyEvent.VK_Y, java.awt.event.InputEvent.CTRL_MASK));
        redoMenuItem.setMnemonic(java.awt.event.KeyEvent.VK_R);
        redoMenuItem.setText(bundle.getString("redoMenuItem")); // NOI18N
        editMenu.add(redoMenuItem);

        menuBar.add(editMenu);

        manageMenu.setMnemonic(java.awt.event.KeyEvent.VK_M);
        manageMenu.setText(bundle.getString("manageMenu")); // NOI18N

        createPersonMenuItem.setMnemonic(java.awt.event.KeyEvent.VK_P);
        createPersonMenuItem.setText(bundle.getString("createPersonMenuItem")); // NOI18N
        manageMenu.add(createPersonMenuItem);

        updatePersonMenuItem.setMnemonic(java.awt.event.KeyEvent.VK_U);
        updatePersonMenuItem.setText(bundle.getString("updatePersonMenuItem")); // NOI18N
        manageMenu.add(updatePersonMenuItem);

        deletePersonMenuItem.setMnemonic(java.awt.event.KeyEvent.VK_D);
        deletePersonMenuItem.setText(bundle.getString("deletePersonMenuItem")); // NOI18N
        manageMenu.add(deletePersonMenuItem);
        manageMenu.add(jSeparator4);

        createMarriageMenuItem.setMnemonic(java.awt.event.KeyEvent.VK_M);
        createMarriageMenuItem.setText(bundle.getString("createMarriageMenuItem")); // NOI18N
        createMarriageMenuItem.setActionCommand(bundle.getString("createMarriageMenuItem")); // NOI18N
        manageMenu.add(createMarriageMenuItem);

        updateMarriageMenuItem.setMnemonic(java.awt.event.KeyEvent.VK_P);
        updateMarriageMenuItem.setText(bundle.getString("updateMarriageMenuItem")); // NOI18N
        updateMarriageMenuItem.setActionCommand(bundle.getString("updateMarriageMenuItem")); // NOI18N
        manageMenu.add(updateMarriageMenuItem);

        deleteMarriageMenuItem.setMnemonic(java.awt.event.KeyEvent.VK_E);
        deleteMarriageMenuItem.setText(bundle.getString("deleteMarriageMenuItem")); // NOI18N
        deleteMarriageMenuItem.setActionCommand(bundle.getString("deleteMarriageMenuItem")); // NOI18N
        manageMenu.add(deleteMarriageMenuItem);
        manageMenu.add(jSeparator5);

        createRelationMenuItem.setMnemonic(java.awt.event.KeyEvent.VK_R);
        createRelationMenuItem.setText(bundle.getString("createRelationMenuItem")); // NOI18N
        createRelationMenuItem.setActionCommand(bundle.getString("createRelationMenuItem")); // NOI18N
        manageMenu.add(createRelationMenuItem);

        deleteRelationMenuItem.setMnemonic(java.awt.event.KeyEvent.VK_L);
        deleteRelationMenuItem.setText(bundle.getString("deleteRelationMenuItem")); // NOI18N
        deleteRelationMenuItem.setActionCommand(bundle.getString("deleteRelationMenuItem")); // NOI18N
        manageMenu.add(deleteRelationMenuItem);

        menuBar.add(manageMenu);

        findMenu.setMnemonic(java.awt.event.KeyEvent.VK_I);
        findMenu.setText(bundle.getString("findMenu")); // NOI18N

        findPersonMenuItem.setMnemonic(java.awt.event.KeyEvent.VK_P);
        findPersonMenuItem.setText(bundle.getString("findPersonMenuItem")); // NOI18N
        findMenu.add(findPersonMenuItem);

        findMarriageMenuItem.setMnemonic(java.awt.event.KeyEvent.VK_M);
        findMarriageMenuItem.setText(bundle.getString("findMarriageMenuItem")); // NOI18N
        findMenu.add(findMarriageMenuItem);

        findRelationMenuItem.setMnemonic(java.awt.event.KeyEvent.VK_R);
        findRelationMenuItem.setText(bundle.getString("findRelationMenuItem")); // NOI18N
        findMenu.add(findRelationMenuItem);

        menuBar.add(findMenu);

        helpMenu.setMnemonic(java.awt.event.KeyEvent.VK_H);
        helpMenu.setText(bundle.getString("helpMenu")); // NOI18N

        aboutMenuItem.setMnemonic(java.awt.event.KeyEvent.VK_A);
        aboutMenuItem.setText(bundle.getString("aboutMenuItem")); // NOI18N
        helpMenu.add(aboutMenuItem);

        menuBar.add(helpMenu);

        setJMenuBar(menuBar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 382, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void newFileMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newFileMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newFileMenuItemActionPerformed

    private void openFileMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openFileMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_openFileMenuItemActionPerformed

    private void undoMenuItemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_undoMenuItemActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_undoMenuItemActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FamilyTreeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FamilyTreeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FamilyTreeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FamilyTreeGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FamilyTreeGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JMenuItem aboutMenuItem;
    private javax.swing.JMenuItem createMarriageMenuItem;
    private javax.swing.JMenuItem createPersonMenuItem;
    private javax.swing.JMenuItem createRelationMenuItem;
    private javax.swing.JMenuItem deleteMarriageMenuItem;
    private javax.swing.JMenuItem deletePersonMenuItem;
    private javax.swing.JMenuItem deleteRelationMenuItem;
    private javax.swing.JMenu editMenu;
    private javax.swing.JMenuItem exitMenuItem;
    private javax.swing.JMenu fileMenu;
    private javax.swing.JMenuItem findMarriageMenuItem;
    private javax.swing.JMenu findMenu;
    private javax.swing.JMenuItem findPersonMenuItem;
    private javax.swing.JMenuItem findRelationMenuItem;
    private javax.swing.JMenu helpMenu;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JPopupMenu.Separator jSeparator1;
    private javax.swing.JPopupMenu.Separator jSeparator2;
    private javax.swing.JPopupMenu.Separator jSeparator3;
    private javax.swing.JPopupMenu.Separator jSeparator4;
    private javax.swing.JPopupMenu.Separator jSeparator5;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JMenu manageMenu;
    private javax.swing.JPanel marriagesPanel;
    private javax.swing.JTable marriagesTable;
    private javax.swing.JMenuBar menuBar;
    private javax.swing.JMenuItem newFileMenuItem;
    private javax.swing.JMenuItem openFileMenuItem;
    private javax.swing.JPanel peoplePanel;
    private javax.swing.JTable peopleTable;
    private javax.swing.JMenuItem redoMenuItem;
    private javax.swing.JPanel relationsPanel;
    private javax.swing.JTable relationsTable;
    private javax.swing.JMenuItem saveFileAsMenuItem;
    private javax.swing.JMenuItem saveFileMenuItem;
    private javax.swing.JPanel treePanel;
    private javax.swing.JMenuItem undoMenuItem;
    private javax.swing.JMenuItem updateMarriageMenuItem;
    private javax.swing.JMenuItem updatePersonMenuItem;
    // End of variables declaration//GEN-END:variables
}
